# Generated by Django 3.2.5 on 2021-07-28 06:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_SprMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Пункт меню')),
                ('icons', models.ImageField(blank=True, upload_to='menu/img/', verbose_name='Иконка')),
                ('links', models.URLField(verbose_name='Ссылка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('cansw', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['order'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
